# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
