# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
