# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
